//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDS
    {
        public int CARDID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string COLOR { get; set; }
        public Nullable<int> STATUSID { get; set; }
        public Nullable<int> USERID { get; set; }
    
        public virtual STATUS STATUS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
